### ISSUE TITLE
Crashing with future client

### ISSUE THREAD

**Issue by 0x15d3** [CrytoPal/Continued-Salhack#14]
Unreported exception thrown!
java.lang.NullPointerException: Cannot invoke "net.futureclient.client.f$jga.f$c()" because "a.f$c" is null
	at net.minecraft.class_355.constant$dlo002$f$c(class_355.java:2084)
	at net.minecraft.class_355.method_1919(class_355.java:156)
	at net.minecraft.class_329.mixinextras$bridge$method_1919$93(class_329.java)
	at net.minecraft.class_329.wrapOperation$bfo000$immediatelyfast$batching(class_329.java:1544)
	at net.minecraft.class_329.method_1753(class_329.java:394)
	at net.minecraft.class_757.method_3192(class_757.java:912)
	at net.minecraft.class_310.method_1523(class_310.java:1327)
	at net.minecraft.class_310.method_1514(class_310.java:888)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

it do crashes when i press tab in server

**Comment by CrytoPal** [comment]
Can you send the full crash log? You can use [mclogs](https://mclo.gs/) to censor personal information

**Comment by 0x15d3** [comment]
https://mclo.gs/dYSspCw
